### ISSUE TITLE
Write Messages

### ISSUE THREAD

**Issue by ngriffiths21** [ngriffiths21/emr#18]
Communicate with other users of the system about patients. Likely separate from the note feature, but in a lot of ways this could be similar to a note that doesn't have an assessment/plan. It should still be associated with a particular patient's chart.

**Comment by zbo14** [comment]
Sounds like you want a message to be a db model. But typically when I think of messaging, I think of real-time messaging like websockets or a message queue like RabbitMQ.. I'm not sure a db is the right place for messages. Anyway, I'm wondering whether the desired functionality can be implemented with Note. Assessment/plan are not required fields, and what about adding an array field that includes the ids of other physicians who may be interested in the note?

**Comment by ngriffiths21** [comment]
The reason to save it to the db is that messages are often part of the
patient record, not just a temporary thing, especially in the case of
consult requests and stuff that will come later on. Does that make sense?

I totally think this can be implemented using note since assessment/plan
aren't required. Maybe even without the array of other people. Notes
already have replies-to, and the only people who should care are the author
of the message and the author of the message it replies to.

One of the things I worry about is distinguishing between notes written
about appointments and notes written for other reasons. You could say one
kind is written to another user, and the other kind is written to the
record itself. Maybe that's the answer. We could add a field for the user
that the note is directed to, and if blank (or some other default value),
the note is considered general documentation about the patient.

Any thoughts?

**Comment by ngriffiths21** [comment]
See #26
