### ISSUE TITLE
Purpose of note.signature?

### ISSUE THREAD

**Issue by zbo14** [ngriffiths21/emr#23]
Note already has `physician_id` and `time_created`

**Comment by ngriffiths21** [comment]
It's common to create a note before finalizing it. For example, a physician might start a note during the visit, then see 5 other pts, then return to the note and edit it before formally signing it. So this is part of a more general concern of being able to save/edit drafts and then sign (which finalizes the document and enters it into a read-only record). The time of signature is just as important as the creation time.

Also, one physician (or midlevel) might start a note, but the note may require a co-signature from an attending, for example. It's useful to have a primary author but also allow other users to sign off.

**Comment by zbo14** [comment]
> but also allow other users to sign off.

So there can be multiple signatures?

It sounds like `note.signature.name` doesn't have to be the name of the physician corresponding to `note.physician_id`. I think it should be `note.signature.physician_id` just to ensure it's unique.

**Comment by ngriffiths21** [comment]
> So there can be multiple signatures?

Yeah, I've seen it before, it should be possible.

> I think it should be note.signature.physician_id

I agree, sounds good.
