### ISSUE TITLE
Rework Note Schema

### ISSUE THREAD

**Issue by ngriffiths21** [ngriffiths21/emr#26]
Issues #9, #18, #19 and #23 can all be addressed by reworking note schema.

### Changes I'm proposing:
- New "addressee" field with 
- New "deferred-until" field
- Updated "signature" field per #23 
- May remove assessment and implement it differently (later, [this](http://library.ahima.org/doc?oid=104997) will be a thing)
- May add "type" field if this seems necessary later

### Implementation:
Flag:
- Is addressed to the user whose help is requested
- Replies to info in previous note such as "order Motrin 400mg TID" or "schedule follow up"
- Empty or nearly empty data section (it's all in the replied-to info)
- Is deferred until it's due (appts don't show up in inboxes until the day of the appt)
- Stays in user's inbox until there is a reply

Message:
- Is addressed to another user
- Likely replies to another message
- Medium-sized data section with contents of message
- Isn't deferred
- May be removed from inbox without reply

Referral:
- Is addressed to a specialist
- Replies to a note in the record with relevant info
- Might be deferred if the specialist appt isn't due yet
- Likely includes short data section including a request of some sort ("pls evaluate for possible ESI")

Regular old note:
- **Not addressed or addressed to default value** ("patient_record")
- Replies to whichever previous note requested the follow up appt, or an initial default value
- Long data section, likely broken up into sections of some kind (SOAP)
- Has an assessment section!

Summary:
- Notes are about patient visits, and are addressed to the record or not addressed
- Referrals/flags bring documented information to the attention of other users & ask for follow up
- Messages just communicate stuff to other users

**Comment by ngriffiths21** [comment]
closed by #27

**Comment by zbo14** [comment]
Can we change `note.addressee` to `note.addressed_to`?

**Comment by ngriffiths21** [comment]
Sure, go for it
